package domain

// ItemCategory defines the high-level grouping of trade goods.
type ItemCategory string

const (
	CategoryRawMaterials ItemCategory = "Raw Materials"
	CategoryIndustrial   ItemCategory = "Industrial"
	CategoryConsumables  ItemCategory = "Consumables"
	CategoryTechnology   ItemCategory = "Technology"
	CategoryLuxury       ItemCategory = "Luxury"
	CategoryContraband   ItemCategory = "Contraband"
)

// ItemName serves as a type-safe identifier for specific goods.
type ItemName string

const (
	// --- SECTOR 1: RAW MATERIALS ---
	ItemHydrogenFuelCells ItemName = "Hydrogen Fuel Cells"
	ItemIronOre           ItemName = "Iron Ore"
	ItemCopperIngots      ItemName = "Copper Ingots"
	ItemTitaniumPlating   ItemName = "Titanium Plating"
	ItemSiliconWafers     ItemName = "Silicon Wafers"
	ItemCarbonFiber       ItemName = "Carbon Fiber"
	ItemRawBauxite        ItemName = "Raw Bauxite"
	ItemLithiumSalts      ItemName = "Lithium Salts"
	ItemCobalt            ItemName = "Cobalt"
	ItemTungstenCarbide   ItemName = "Tungsten Carbide"
	ItemGoldBullion       ItemName = "Gold Bullion"
	ItemPlatinumCrystals  ItemName = "Platinum Crystals"
	ItemUraniumOre        ItemName = "Uranium Ore"
	ItemPlutoniumRods     ItemName = "Plutonium Rods"
	ItemHelium3           ItemName = "Helium-3"
	ItemDeuterium         ItemName = "Deuterium"
	ItemWaterIce          ItemName = "Water Ice"
	ItemOxygenCanisters   ItemName = "Oxygen Canisters"
	ItemNitrogenTanks     ItemName = "Nitrogen Tanks"
	ItemRawBiomass        ItemName = "Raw Biomass"
	ItemScrapMetal        ItemName = "Scrap Metal"
	ItemPolymerResins     ItemName = "Polymer Resins"
	ItemGrapheneSheets    ItemName = "Graphene Sheets"
	ItemObsidianGlass     ItemName = "Obsidian Glass"
	ItemLiquidMethane     ItemName = "Liquid Methane"

	// --- SECTOR 2: INDUSTRIAL ---
	ItemSteelBeams             ItemName = "Steel Beams"
	ItemCeramicComposites      ItemName = "Ceramic Composites"
	ItemInsulatedWiring        ItemName = "Insulated Wiring"
	ItemHydraulicFluids        ItemName = "Hydraulic Fluids"
	ItemMagneticCoils          ItemName = "Magnetic Coils"
	ItemSolarPanels            ItemName = "Solar Panels"
	ItemRadiationShielding     ItemName = "Radiation Shielding"
	ItemTransparisteel         ItemName = "Transparisteel"
	ItemHullPlating            ItemName = "Hull Plating"
	ItemBallBearings           ItemName = "Ball Bearings"
	ItemIndustrialLubricants   ItemName = "Industrial Lubricants"
	ItemFusionRegulators       ItemName = "Fusion Regulators"
	ItemCircuitBoards          ItemName = "Circuit Boards"
	ItemMicroprocessors        ItemName = "Microprocessors"
	ItemOpticalFibers          ItemName = "Optical Fibers"
	ItemNanotubes              ItemName = "Nanotubes"
	ItemConcreteSlabs          ItemName = "Concrete Slabs"
	ItemPrefabHabitationUnits  ItemName = "Prefab Habitation Units"
	ItemLifeSupportFilters     ItemName = "Life Support Filters"
	ItemWasteRecyclers         ItemName = "Waste Recyclers"
	ItemDrillingHeads          ItemName = "Drilling Heads"
	ItemConveyorBelts          ItemName = "Conveyor Belts"
	ItemGravPlates             ItemName = "Grav-Plates"
	ItemDockingClamps          ItemName = "Docking Clamps"
	ItemAirLockSeals           ItemName = "Air Lock Seals"

	// --- SECTOR 3: CONSUMABLES ---
	ItemNutrientPaste        ItemName = "Nutrient Paste"
	ItemSyntheticMeat        ItemName = "Synthetic Meat"
	ItemGrainSacks           ItemName = "Grain Sacks"
	ItemPurifiedWater        ItemName = "Purified Water"
	ItemDehydratedVegetables ItemName = "Dehydrated Vegetables"
	ItemSoyProtein           ItemName = "Soy Protein"
	ItemAlgaeMash            ItemName = "Algae Mash"
	ItemCoffeeBeans          ItemName = "Coffee Beans"
	ItemTeaLeaves            ItemName = "Tea Leaves"
	ItemSpices               ItemName = "Spices"
	ItemExoticFruits         ItemName = "Exotic Fruits"
	ItemLivestock            ItemName = "Livestock"
	ItemFertilizer           ItemName = "Fertilizer"
	ItemSeeds                ItemName = "Seeds"
	ItemAntibiotics          ItemName = "Antibiotics"
	ItemFirstAidKits         ItemName = "First Aid Kits"
	ItemBandages             ItemName = "Bandages"
	ItemVitamins             ItemName = "Vitamins"
	ItemStimPacks            ItemName = "Stim-Packs"
	ItemAlcohol              ItemName = "Alcohol"
	ItemDistilledSpirits     ItemName = "Distilled Spirits"
	ItemCigarettes           ItemName = "Cigarettes"
	ItemChocolate            ItemName = "Chocolate"
	ItemHoney                ItemName = "Honey"
	ItemDairyProducts        ItemName = "Dairy Products"

	// --- SECTOR 4: TECHNOLOGY ---
	ItemQuantumProcessors     ItemName = "Quantum Processors"
	ItemAICoresBasic          ItemName = "AI Cores (Basic)"
	ItemAICoresAdvanced       ItemName = "AI Cores (Advanced)"
	ItemHolographicProjectors ItemName = "Holographic Projectors"
	ItemNavComputerChips      ItemName = "Nav-Computer Chips"
	ItemSensorArrays          ItemName = "Sensor Arrays"
	ItemTargetingLogicBoards  ItemName = "Targeting Logic Boards"
	ItemCommunicationRelays   ItemName = "Communication Relays"
	ItemTranslationMatrix     ItemName = "Translation Matrix"
	ItemCryptographicKeys     ItemName = "Cryptographic Keys"
	ItemDataStorageDrives     ItemName = "Data Storage Drives"
	ItemServerRacks           ItemName = "Server Racks"
	ItemRoboticArms           ItemName = "Robotic Arms"
	ItemDroneChassis          ItemName = "Drone Chassis"
	ItemCyberneticLimbs       ItemName = "Cybernetic Limbs"
	ItemOcularImplants        ItemName = "Ocular Implants"
	ItemNeuralInterfaces      ItemName = "Neural Interfaces"
	ItemMedicalScanners       ItemName = "Medical Scanners"
	ItemTerraformingMicrobes  ItemName = "Terraforming Microbes"
	ItemAtmosphericProcessors ItemName = "Atmospheric Processors"
	ItemEncryptionBreakers    ItemName = "Encryption Breakers"
	ItemSecurityFirewalls     ItemName = "Security Firewalls"
	ItemVRHeadsets            ItemName = "VR Headsets"
	ItemPowerInverters        ItemName = "Power Inverters"
	ItemBatteryBanks          ItemName = "Battery Banks"

	// --- SECTOR 5: LUXURY ---
	ItemSilk                 ItemName = "Silk"
	ItemDesignerClothing     ItemName = "Designer Clothing"
	ItemJewelry              ItemName = "Jewelry"
	ItemGemstones            ItemName = "Gemstones"
	ItemSculptures           ItemName = "Sculptures"
	ItemPaintings            ItemName = "Paintings"
	ItemAncientArtifacts     ItemName = "Ancient Artifacts"
	ItemRareBooks            ItemName = "Rare Books"
	ItemVinylRecords         ItemName = "Vinyl Records"
	ItemFineWine             ItemName = "Fine Wine"
	ItemAgedWhiskey          ItemName = "Aged Whiskey"
	ItemPerfume              ItemName = "Perfume"
	ItemExoticPets           ItemName = "Exotic Pets"
	ItemMusicalInstruments   ItemName = "Musical Instruments"
	ItemCeremonialRobes      ItemName = "Ceremonial Robes"
	ItemRelics               ItemName = "Relics"
	ItemTrophies             ItemName = "Trophies"
	ItemVRExperiences        ItemName = "VR Experiences"
	ItemPersonalButlers      ItemName = "Personal Butlers"
	ItemRestoredClassicCars  ItemName = "Restored Classic Cars"
	ItemGoldPlatedWeapons    ItemName = "Gold Plated Weapons"
	ItemAlienPottery         ItemName = "Alien Pottery"
	ItemGeneEditedFlowers    ItemName = "Gene-Edited Flowers"
	ItemCaviar               ItemName = "Caviar"
	ItemTruffles             ItemName = "Truffles"

	// --- SECTOR 6: CONTRABAND ---
	ItemNarcotics             ItemName = "Narcotics"
	ItemStolenIDChips         ItemName = "Stolen ID Chips"
	ItemHackedCreditSticks    ItemName = "Hacked Credit Sticks"
	ItemUnregisteredWeapons   ItemName = "Unregistered Weapons"
	ItemCombatStims           ItemName = "Combat Stims"
	ItemSlaveCollars          ItemName = "Slave Collars"
	ItemCounterfeitCurrency   ItemName = "Counterfeit Currency"
	ItemBootlegSoftware       ItemName = "Bootleg Software"
	ItemAILimitersDisabled    ItemName = "AI Limiters (Disabled)"
	ItemHarvestedOrgans       ItemName = "Harvested Organs"
	ItemEndangeredSpecies     ItemName = "Endangered Species"
	ItemRadioactiveWaste      ItemName = "Radioactive Waste"
	ItemExplosives            ItemName = "Explosives"
	ItemPoison                ItemName = "Poison"
	ItemSpyware               ItemName = "Spyware"
	ItemTortureDevices        ItemName = "Torture Devices"
	ItemRelicFragments        ItemName = "Relic Fragments"
	ItemMindWipeDrugs         ItemName = "Mind-Wipe Drugs"
	ItemFugitiveBiometrics    ItemName = "Fugitive Biometrics"
	ItemRedMercury            ItemName = "Red Mercury"
	ItemSentientAICode        ItemName = "Sentient AI Code"
	ItemCloneVats             ItemName = "Clone Vats"
	ItemGeneWarfareCanisters  ItemName = "Gene-Warfare Canisters"
	ItemPsychoActiveSpores    ItemName = "Psycho-Active Spores"
	ItemTheGoodStuff          ItemName = "The Good Stuff"
)